disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - opening_brace

# rule identifiers to opt in
opt_in_rules:
  - fatal_error_message
  - first_where
  - closure_end_indentation
  - closure_spacing
  - empty_count

function_body_length:
 - 10 # warning
 - 15 # error

identifier_name:
  min_length: # only min_length
    error: 1 
    warning: 1
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

file_length:
  warning: 400
  error: 1000

statement_position:
  statement_mode: uncuddled_else

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: iPhone # excluded via string

line_length:
  warning: 120
  error: 200
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: false

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods

# custom_rules:
#     invalid_open_brace:
#      name: "Open brace should start on its own line"
#      regex: "\\S[ \\t]+\\{"
#      message: "Open brace should start on its own line"
#      severity: warning

